# Generated by Django 5.1.2 on 2024-10-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KohonenConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neurons', models.IntegerField()),
                ('learning_rate', models.FloatField()),
                ('competition_type', models.CharField(max_length=100)),
                ('iterations', models.IntegerField()),
            ],
        ),
    ]
