# Generated by Django 5.1.2 on 2024-10-10 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kohonen_api', '0002_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kohonenconfig',
            name='learning_rate',
        ),
    ]
