# Generated by Django 5.1.2 on 2024-10-10 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kohonen_api', '0003_remove_kohonenconfig_learning_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kohonen_api.image')),
            ],
        ),
    ]
